server:
  port: 8081

spring:
  application:
    name: spring-mybatis
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    url: jdbc:postgresql://localhost:7070/mybatis_tutorial_db
    username: mybatis
    password: mypassword

mybatis:
  mapper-locations: classpath:mapper/*.xml